{% set name = "watchtower" %}
{% set version = "3.3.1" %}

package:
  name: watchtower
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/watchtower-{{ version }}.tar.gz
  sha256: 5e654f52b54b39e279592d6c18a033b22cfbffda676f5b3cf6dfef712ed5738c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - boto3 >=1.9.253,<2

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - watchtower
  commands:
    - pip check

about:
  home: http://github.com/kislyuk/watchtower
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python CloudWatch Logging: Log Analytics and Application Intelligence'

  description: |
    Watchtower is a log handler for Amazon Web Services CloudWatch Logs. CloudWatch 
    Logs is a log management service built into AWS. It is conceptually similar to 
    services like Splunk and Loggly, but is more lightweight, cheaper, and tightly
    integrated with the rest of AWS.  Watchtower, in turn, is a lightweight adapter
    between the Python logging system and CloudWatch Logs. It uses the boto3 AWS 
    SDK, and lets you plug your application logging directly into CloudWatch without
    the need to install a system-wide log collector. It aggregates logs into batches 
    to avoid sending an API request per each log message, while guaranteeing a 
    delivery deadline (60 seconds by default).  
  doc_url: https://watchtower.readthedocs.io/
  dev_url: https://github.com/kislyuk/watchtower

extra:
  recipe-maintainers:
    - mcg1969
    - xylar
    - ericdill
