{% set name = "watchtower" %}
{% set version = "3.2.0" %}

package:
  name: watchtower
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/watchtower-{{ version }}.tar.gz
  sha256: 7d515b2d0ae0d36168d3b32937e7f79c19b3efd25bbd16bcda233a092666b98c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - boto3 >=1.9.253,<2

test:
  requires:
    - pip
  imports:
    - watchtower
  commands:
    - pip check

about:
  home: http://github.com/kislyuk/watchtower
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python CloudWatch Logging: Log Analytics and Application Intelligence'

  description: |
    Watchtower is a log handler for Amazon Web Services CloudWatch Logs. CloudWatch 
    Logs is a log management service built into AWS. It is conceptually similar to 
    services like Splunk and Loggly, but is more lightweight, cheaper, and tightly
    integrated with the rest of AWS.  Watchtower, in turn, is a lightweight adapter
    between the Python logging system and CloudWatch Logs. It uses the boto3 AWS 
    SDK, and lets you plug your application logging directly into CloudWatch without
    the need to install a system-wide log collector. It aggregates logs into batches 
    to avoid sending an API request per each log message, while guaranteeing a 
    delivery deadline (60 seconds by default).  
  doc_url: https://watchtower.readthedocs.io/
  dev_url: https://github.com/kislyuk/watchtower

extra:
  recipe-maintainers:
    - mcg1969
    - xylar
    - ericdill
